### ISSUE TITLE
go-coding-in-go-way-cn.slide 是怎么生成ppt的？请教

### ISSUE THREAD

**Issue by jinleileiking** [bigwhite/talks#1]

**Comment by bigwhite** [comment]
no ppt，just pdf.  The pdf file is generated by using the browser's print to pdf.

**Comment by WenzheLiu** [comment]
有没有办法通过.slide文件生成ppt？或者通过ppt生成.slide文件？

**Comment by bigwhite** [comment]
似乎还没有直接通过.slide生成ppt的方法。但是可以试试.slide -> pdf -> ppt。有很多online的pdf 2 ppt的工具和服务。
